"""
core/report.py

Generates a clean, self-contained HTML report (plus a raw JSON export)
summarizing a WiFiSentinel engagement: scoped targets, scan results,
capture attempts, and crack outcomes. Designed to be handed to a
client alongside a pentest write-up.
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict, is_dataclass
from datetime import datetime
from typing import Any, Dict, List

from ..utils.logger import get_logger

log = get_logger(__name__)

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>WiFiSentinel Engagement Report - {client_name}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0; background: #0f1117; color: #e6e6e6; }}
  header {{ background: #161a23; padding: 28px 40px; border-bottom: 3px solid #3ddc97; }}
  header h1 {{ margin: 0 0 4px 0; font-size: 22px; }}
  header p {{ margin: 2px 0; color: #9aa4b2; font-size: 13px; }}
  main {{ padding: 24px 40px 60px; max-width: 1100px; margin: 0 auto; }}
  section {{ margin-bottom: 36px; }}
  h2 {{ font-size: 16px; color: #3ddc97; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid #2a2f3a; padding-bottom: 8px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th, td {{ text-align: left; padding: 8px 10px; border-bottom: 1px solid #232734; }}
  th {{ color: #9aa4b2; font-weight: 600; }}
  .tag {{ display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 600; }}
  .tag.ok {{ background: #123d2b; color: #3ddc97; }}
  .tag.fail {{ background: #3d1414; color: #ff6b6b; }}
  .badge {{ background: #1c2130; border: 1px solid #2a2f3a; border-radius: 8px; padding: 16px; }}
  footer {{ text-align: center; color: #5b6472; font-size: 12px; padding: 20px; }}
</style>
</head>
<body>
<header>
  <h1>WiFiSentinel Engagement Report</h1>
  <p>Client / Scope Owner: {client_name}</p>
  <p>Authorization reference: {authorization_reference}</p>
  <p>Generated: {generated_at}</p>
</header>
<main>
  <section>
    <h2>Access Points Discovered</h2>
    <table>
      <tr><th>BSSID</th><th>ESSID</th><th>Channel</th><th>Privacy</th><th>Power</th></tr>
      {ap_rows}
    </table>
  </section>
  <section>
    <h2>Capture Attempts</h2>
    <table>
      <tr><th>Target</th><th>Method</th><th>Result</th><th>Notes</th></tr>
      {capture_rows}
    </table>
  </section>
  <section>
    <h2>Crack Results</h2>
    <table>
      <tr><th>Target</th><th>Engine</th><th>Result</th><th>Key</th><th>Time (s)</th></tr>
      {crack_rows}
    </table>
  </section>
</main>
<footer>Generated by WiFiSentinel &middot; For authorized security testing only</footer>
</body>
</html>
"""


def _to_dict(obj: Any) -> Dict:
    return asdict(obj) if is_dataclass(obj) else dict(obj)


def _ap_row(ap: Dict) -> str:
    return (f"<tr><td>{ap.get('bssid','')}</td><td>{ap.get('essid','')}</td>"
            f"<td>{ap.get('channel','')}</td><td>{ap.get('privacy','')}</td>"
            f"<td>{ap.get('power','')}</td></tr>")


def _capture_row(target: str, cap: Dict) -> str:
    tag = '<span class="tag ok">CAPTURED</span>' if cap.get("success") else '<span class="tag fail">NO CAPTURE</span>'
    return (f"<tr><td>{target}</td><td>{cap.get('method','')}</td><td>{tag}</td>"
            f"<td>{cap.get('message','')}</td></tr>")


def _crack_row(target: str, crack: Dict) -> str:
    tag = '<span class="tag ok">CRACKED</span>' if crack.get("success") else '<span class="tag fail">NOT CRACKED</span>'
    key = crack.get("key") or "-"
    return (f"<tr><td>{target}</td><td>{crack.get('engine','')}</td><td>{tag}</td>"
            f"<td>{key}</td><td>{crack.get('seconds_elapsed', 0):.1f}</td></tr>")


def generate_report(
    output_path: str,
    client_name: str,
    authorization_reference: str,
    access_points: List[Any],
    captures: List[Dict],
    cracks: List[Dict],
) -> str:
    """
    captures / cracks: list of dicts like
      {"target": "AA:BB:CC:DD:EE:FF", "result": CaptureResult/CrackResult}
    """
    ap_dicts = [_to_dict(ap) for ap in access_points]

    ap_rows = "\n".join(_ap_row(ap) for ap in ap_dicts) or "<tr><td colspan='5'>No APs recorded</td></tr>"
    capture_rows = "\n".join(
        _capture_row(c["target"], _to_dict(c["result"])) for c in captures
    ) or "<tr><td colspan='4'>No capture attempts recorded</td></tr>"
    crack_rows = "\n".join(
        _crack_row(c["target"], _to_dict(c["result"])) for c in cracks
    ) or "<tr><td colspan='5'>No crack attempts recorded</td></tr>"

    html = _HTML_TEMPLATE.format(
        client_name=client_name,
        authorization_reference=authorization_reference,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        ap_rows=ap_rows,
        capture_rows=capture_rows,
        crack_rows=crack_rows,
    )

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    json_path = output_path.rsplit(".", 1)[0] + ".json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "client_name": client_name,
                "authorization_reference": authorization_reference,
                "generated_at": datetime.now().isoformat(),
                "access_points": ap_dicts,
                "captures": [{"target": c["target"], **_to_dict(c["result"])} for c in captures],
                "cracks": [{"target": c["target"], **_to_dict(c["result"])} for c in cracks],
            },
            f,
            indent=2,
        )

    log.info("Report written to %s (+ %s)", output_path, json_path)
    return output_path
